services:
  - type: web
    name: portal-residencial-temporada
    runtime: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn portal_residencial.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,www.residencialtemporada.com.br,residencialtemporada.com.br,portal.residencialtemporada.com.br"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.4"