# Generated by Django 5.2.14 on 2026-05-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Residencial Temporada', max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('capacidade', models.PositiveIntegerField(default=2)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='unidades.unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado'), ('manutencao', 'Manutenção')], default='livre', max_length=20)),
                ('valor_sugerido', models.DecimalField(decimal_places=2, default=750, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='unidades.quarto')),
            ],
            options={
                'ordering': ['quarto__nome', 'codigo'],
                'unique_together': {('quarto', 'codigo')},
            },
        ),
    ]
