# Generated by Django 5.2.14 on 2026-05-30 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('empresa', models.CharField(blank=True, max_length=160)),
                ('cidade_origem', models.CharField(blank=True, max_length=120)),
                ('emergencia_nome', models.CharField(max_length=160)),
                ('emergencia_parentesco', models.CharField(max_length=80)),
                ('emergencia_telefone', models.CharField(max_length=30)),
                ('emergencia_whatsapp', models.CharField(blank=True, max_length=30)),
                ('documento_rg_cnh', models.FileField(blank=True, null=True, upload_to='documentos/candidatos/')),
                ('comprovante_residencia', models.FileField(blank=True, null=True, upload_to='documentos/candidatos/')),
                ('foto_pessoal', models.FileField(blank=True, null=True, upload_to='documentos/candidatos/')),
                ('fuma', models.BooleanField(default=False)),
                ('aceita_regras', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('espera', 'Lista de espera'), ('convertido', 'Convertido em morador')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profissao', models.CharField(blank=True, max_length=120)),
                ('empresa', models.CharField(blank=True, max_length=160)),
                ('cidade_origem', models.CharField(blank=True, max_length=120)),
                ('valor_contratado', models.DecimalField(decimal_places=2, default=750, max_digits=10)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('inadimplente', 'Inadimplente'), ('renovacao', 'Em renovação')], default='ativo', max_length=20)),
                ('chave_entregue', models.BooleanField(default=False)),
                ('controle_portao_entregue', models.BooleanField(default=False)),
                ('wifi_entregue', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('leito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.leito')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.quarto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando assinatura'), ('ativo', 'Ativo'), ('renovado', 'Renovado'), ('encerrado', 'Encerrado')], default='aguardando', max_length=20)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('assinado', models.BooleanField(default=False)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='moradores.morador')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('parentesco', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principal', models.BooleanField(default=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_emergencia', to='moradores.morador')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('advertencia', 'Advertência'), ('manutencao', 'Manutenção'), ('reclamacao', 'Reclamação'), ('observacao', 'Observação')], max_length=20)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='moradores.morador')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
