# Generated by Django 5.2.14 on 2026-06-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='atestado_antecedentes_estadual',
            field=models.FileField(blank=True, null=True, upload_to='documentos/candidatos/', verbose_name='Atestado de Antecedentes Criminais (Estadual - SSP/SP)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='atestado_antecedentes_federal',
            field=models.FileField(blank=True, null=True, upload_to='documentos/candidatos/', verbose_name='Atestado de Antecedentes Criminais (Federal - Polícia Federal)'),
        ),
    ]
