# Generated by Django 5.2.14 on 2026-05-30 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='Exemplo: 2026-06', max_length=7)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='moradores.contrato')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='moradores.morador')),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
    ]
